import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const code=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('let state='));
function page(){const dom=new JSDOM(html,{url:'https://staging.example',runScripts:'outside-only'});dom.window.console.warn=()=>{};dom.window.requestAnimationFrame=()=>{};dom.window.alert=()=>{};dom.window.confirm=()=>true;return dom;}
const delay=()=>new Promise(resolve=>setTimeout(resolve,0));
test('timer starts and saves locally without account, network or IndexedDB',async()=>{const dom=page(),w=dom.window;w.eval(code);await delay();w.document.getElementById('mainBtn').click();w.document.getElementById('mainBtn').click();w.document.getElementById('saveRace').click();assert.equal(w.raceSplitBridge.getHistory().length,1);const keys=Object.keys(w.localStorage);const saved=keys.map(k=>JSON.parse(w.localStorage.getItem(k))).find(v=>v.history);assert.equal(saved.history.length,1);assert.ok(saved.start);assert.ok(!saved.history[0].ownerId);dom.window.close()});
test('active and paused timer survives reload with local state preserved',async()=>{const first=page();first.window.eval(code);await delay();first.window.document.getElementById('mainBtn').click();first.window.document.getElementById('pauseBtn').click();const k=Object.keys(first.window.localStorage)[0],raw=first.window.localStorage.getItem(k),before=JSON.parse(raw);const second=page();second.window.localStorage.setItem(k,raw);second.window.eval(code);await delay();const after=JSON.parse(second.window.localStorage.getItem(k));assert.equal(after.start,before.start);assert.equal(after.pausedAt,before.pausedAt);assert.equal(second.window.document.getElementById('status').textContent,'PAUSED');first.window.close();second.window.close()});
test('IndexedDB recovery precedes empty initial-state save',async()=>{const dom=page(),w=dom.window,record={raw:JSON.stringify({start:Date.now()-10000,ends:[5000],history:[],pausedMs:0,finished:false})};const writes=[];const database={objectStoreNames:{contains:()=>true},transaction(_store,mode){const tx={objectStore(){return {get(){const request={};queueMicrotask(()=>{request.result=record;request.onsuccess?.()});return request},put(value){writes.push(value);queueMicrotask(()=>tx.oncomplete?.());return {}}}}};return tx}};w.indexedDB={open(){const req={};queueMicrotask(()=>{req.result=database;req.onsuccess?.()});return req}};w.eval(code);await delay();assert.equal(JSON.parse(w.localStorage.getItem(Object.keys(w.localStorage)[0])).start,JSON.parse(record.raw).start);assert.ok(writes.every(v=>JSON.parse(v.raw).start));dom.window.close()});
test('unified setup opens first; start and reset stay in race until explicit Setup',async()=>{const dom=page(),w=dom.window,root=w.document.documentElement,$=id=>w.document.getElementById(id);const style=w.document.createElement('style');style.textContent=readFileSync(new URL('../public/brand/targets.css',import.meta.url),'utf8');w.document.head.append(style);w.eval(code);await delay();w.eval(readFileSync(new URL('../public/brand/appearance.js',import.meta.url),'utf8'));await delay();assert.equal(root.dataset.raceMode,'off');assert.ok($('setupPanel').contains($('raceControls')));assert.ok($('setupPanel').contains($('templateSelect')));$('mainBtn').click();assert.equal(root.dataset.raceMode,'on');assert.equal(w.getComputedStyle($('setupPanel')).display,'none');const before=w.localStorage.getItem('racesplit-v3');$('revealRaceSetup').click();assert.equal(root.dataset.raceMode,'off');assert.notEqual(w.getComputedStyle($('setupPanel')).display,'none');assert.equal(w.localStorage.getItem('racesplit-v3'),before);assert.equal($('templateSelect').disabled,true);$('raceMode').click();$('pauseBtn').click();assert.equal(root.dataset.raceMode,'on');$('resetBtn').click();assert.equal(root.dataset.timerActive,'false');assert.equal(root.dataset.raceMode,'on');assert.equal(w.getComputedStyle($('setupPanel')).display,'none');assert.notEqual(w.getComputedStyle($('revealRaceSetup')).display,'none');$('revealRaceSetup').click();assert.equal(root.dataset.raceMode,'off');assert.equal($('templateSelect').disabled,false);assert.equal($('setupPanel').classList.contains('setupCollapsed'),false);assert.equal(w.raceSplitBridge.getHistory().length,0);w.close();});
test('no-run events summarize transition time and completed count; running events keep Run',async()=>{for(const [selected,ends,label,total] of [['strong',[10000,13000,33000,38000],'Transitions · 2 / 9','00:08'],['mile',[10000,13000,33000,38000],'Run','00:30']]){const d=page(),w=d.window;w.localStorage.setItem('racesplit-v3',JSON.stringify({selected,start:Date.now()-60000,ends,pausedAt:Date.now(),pausedMs:0}));w.eval(code);await delay();assert.equal(w.document.getElementById('runLabel').textContent,label);assert.equal(w.document.getElementById('runTotal').textContent,total);w.document.getElementById('undoBtn').click();if(selected==='strong'){assert.equal(w.document.getElementById('runLabel').textContent,'Transitions · 1 / 9');assert.equal(w.document.getElementById('runTotal').textContent,'00:03');}w.close();}});
test('idle revisit opens Setup even with old Race Mode preference; active reload returns to race',async()=>{for(const start of [null,Date.now()-10000]){const d=page(),w=d.window;w.localStorage.setItem('racesplit-v3',JSON.stringify({selected:'strong',start,ends:[],finished:false}));w.localStorage.setItem('racesplit-appearance-v1',JSON.stringify({theme:'light',raceMode:true}));w.eval(code);await delay();w.eval(readFileSync(new URL('../public/brand/appearance.js',import.meta.url),'utf8'));await delay();assert.equal(w.document.documentElement.dataset.raceMode,start?'on':'off');assert.equal(w.document.getElementById('templateSelect').disabled,!!start);w.close();}});
