import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { handleAuth,hash,passwordHash,verifyPassword } from '../src/auth.mjs';
import { handleData } from '../src/data-api.mjs';
import { mergeCloud,racePayload } from '../public/modules/cloud.mjs';
function database(){const db=new DatabaseSync(':memory:');for(const f of ['0001_initial.sql','0002_auth_sync.sql'])db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const wrap=(sql,args=[])=>({bind(...v){return wrap(sql,v)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}});return {db,prepare:wrap,async batch(statements){db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results}catch(e){db.exec('ROLLBACK');throw e}}};}
const origin='https://staging.example';
function request(path,method='GET',body,token,customOrigin=origin){return new Request(origin+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{Origin:customOrigin}:{}),...(token?{Cookie:'rs_session='+token,...(token.startsWith('token-user-')?{'X-RaceSplit-Account':token.replace('token-','')}:{})}:{})},...(body?{body:JSON.stringify(body)}:{})})}
async function setup(){const DB=database();for(const [id,email] of [['user-one','one@example.com'],['user-two','two@example.com']]){await DB.prepare('INSERT INTO users(id,email,email_verified,password_hash) VALUES(?,?,1,?)').bind(id,email,await passwordHash('long-secure-password')).run();await DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+1 day'))").bind(id,id,await hash('token-'+id)).run();}return {DB};}
const data=(r,e)=>handleData(r,e,new URL(r.url));const auth=(r,e)=>handleAuth(r,e,new URL(r.url));
test('password hashing salts and verifies',async()=>{const a=await passwordHash('long-secure-password'),b=await passwordHash('long-secure-password');assert.notEqual(a,b);assert.equal(await verifyPassword('long-secure-password',a),true);assert.equal(await verifyPassword('wrong-password',a),false)});
test('login returns secure cookie; logout revokes it',async()=>{const env=await setup();const res=await auth(request('/api/auth/login','POST',{email:'one@example.com',password:'long-secure-password'}),env);assert.equal(res.status,200);const c=res.headers.get('set-cookie');for(const flag of ['HttpOnly','Secure','SameSite=Lax'])assert.ok(c.includes(flag));const token=c.split(';')[0].split('=')[1];assert.equal((await data(request('/api/me','GET',null,token),env)).status,200);await auth(request('/api/auth/logout','POST',null,token),env);assert.equal((await data(request('/api/me','GET',null,token),env)).status,401)});
test('unverified and expired sessions denied; cross-origin mutations denied',async()=>{const env=await setup();await env.DB.prepare('UPDATE users SET email_verified=0 WHERE id=?').bind('user-one').run();assert.equal((await data(request('/api/me','GET',null,'token-user-one'),env)).status,401);await env.DB.prepare("UPDATE sessions SET expires_at=datetime('now','-1 day') WHERE user_id=?").bind('user-two').run();assert.equal((await data(request('/api/me','GET',null,'token-user-two'),env)).status,401);assert.equal((await auth(request('/api/auth/login','POST',{email:'one@example.com',password:'long-secure-password'},null,'https://evil.example'),env)).status,403)});
test('athlete ownership, rename and delete',async()=>{const env=await setup();assert.equal((await data(request('/api/athletes','POST',{id:'athlete-one',name:'Emma'},'token-user-one'),env)).status,201);const other=await data(request('/api/athletes','GET',null,'token-user-two'),env);assert.deepEqual((await other.json()).athletes,[]);assert.equal((await data(request('/api/athletes/athlete-one','PATCH',{name:'Wrong'},'token-user-two'),env)).status,404);assert.equal((await data(request('/api/athletes/athlete-one','PATCH',{name:'Emma M'},'token-user-one'),env)).status,200);await data(request('/api/athletes/athlete-one','DELETE',null,'token-user-one'),env);assert.equal((await (await data(request('/api/athletes','GET',null,'token-user-one'),env)).json()).athletes.length,0)});
test('race create, replay after lost response, update, conflict and user isolation',async()=>{const env=await setup(),p={clientId:'race-client',mutationId:'mutation-first',expectedRevision:0,eventName:'DEKA',eventSnapshot:{event:{name:'DEKA'},ends:[1000]},elapsedMs:1000};const put=(body,token='token-user-one')=>data(request('/api/races/race-one','PUT',body,token),env);assert.equal((await put(p)).status,201);assert.equal((await (await put(p)).json()).revision,1);assert.equal((await put({...p,mutationId:'mutation-wrong'})).status,409);assert.equal((await put({...p,expectedRevision:1,mutationId:'mutation-second'})).status,200);assert.equal((await (await put({...p,expectedRevision:1,mutationId:'mutation-second'})).json()).revision,2);assert.equal((await put(p,'token-user-two')).status,409);assert.deepEqual((await (await data(request('/api/races','GET',null,'token-user-two'),env)).json()).races,[]);assert.equal((await put({...p,elapsedMs:-1})).status,400)});
test('race rejects another account athlete and CSRF',async()=>{const env=await setup();await data(request('/api/athletes','POST',{id:'athlete-two',name:'Other'},'token-user-two'),env);const p={clientId:'race-client',mutationId:'mutation-first',expectedRevision:0,eventName:'DEKA',eventSnapshot:{},athleteId:'athlete-two'};assert.equal((await data(request('/api/races/race-one','PUT',p,'token-user-one'),env)).status,400);assert.equal((await data(request('/api/races/race-one','PUT',p,'token-user-one','https://evil.example'),env)).status,403)});
test('verification token expires and is consumed',async()=>{const env=await setup();await env.DB.prepare('UPDATE users SET email_verified=0 WHERE id=?').bind('user-one').run();await env.DB.prepare("INSERT INTO auth_tokens VALUES(?,?,datetime('now','+1 hour'))").bind(await hash('verification-token'),'user-one').run();assert.equal((await auth(request('/api/auth/verify','POST',{token:'verification-token'}),env)).status,200);assert.equal((await auth(request('/api/auth/verify','POST',{token:'verification-token'}),env)).status,400)});
test('missing credentials fail closed; OAuth callback rejects unbound state',async()=>{const env=await setup();assert.equal((await auth(request('/api/auth/google'),env)).status,503);assert.equal((await auth(request('/api/auth/register','POST',{email:'new@example.com',password:'long-secure-password'}),env)).status,503);assert.equal((await auth(request('/api/auth/callback/google?state=forged&code=forged'),env)).status,400)});
test('rate limit returns 429',async()=>{const env=await setup();for(let i=0;i<30;i++)assert.equal((await auth(request('/api/auth/config'),env)).status,200);assert.equal((await auth(request('/api/auth/config'),env)).status,429)});
test('cloud merge retains pending local conflict and other device races',()=>{const local=[{cloudId:'race-one',ownerId:'user-one',pendingCloud:true,event:{name:'Local'},ends:[10]}];const rows=[{id:'race-one',revision:2,event_snapshot:{event:{name:'Cloud'},ends:[20]}},{id:'race-two',revision:1,event_snapshot:{event:{name:'Other device'},ends:[30]}}];const result=mergeCloud(local,rows,'user-one');assert.equal(result.length,2);assert.equal(result[0].event.name,'Local');assert.equal(result[1].cloudRevision,1);assert.equal(racePayload({...local[0],start:1},'mutation-one').elapsedMs,10)});
test('soft deletion uses revision checks and propagates tombstones',async()=>{const env=await setup(),p={clientId:'race-client',mutationId:'mutation-first',expectedRevision:0,eventName:'DEKA',eventSnapshot:{event:{name:'DEKA'},ends:[1000]}};await data(request('/api/races/race-one','PUT',p,'token-user-one'),env);assert.equal((await data(request('/api/races/race-one','DELETE',{expectedRevision:0},'token-user-one'),env)).status,409);assert.equal((await data(request('/api/races/race-one','DELETE',{expectedRevision:1},'token-user-one'),env)).status,200);const rows=(await (await data(request('/api/races?includeDeleted=1','GET',null,'token-user-one'),env)).json()).races;assert.ok(rows[0].deleted_at);assert.deepEqual(mergeCloud([{cloudId:'race-one',ownerId:'user-one'}],rows,'user-one'),[])});
test('registration sends token without storing raw token; verification gates login',async()=>{const env={...await setup(),RESEND_API_KEY:'test-key',RESEND_FROM_EMAIL:'RaceSplit <test@example.com>'},originalFetch=globalThis.fetch;let sent;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');sent=JSON.parse(options.body);return Response.json({id:'mail'})};try{const credentials={email:'new@example.com',password:'long-secure-password'};assert.equal((await auth(request('/api/auth/register','POST',credentials),env)).status,200);assert.equal((await auth(request('/api/auth/login','POST',credentials),env)).status,403);const token=sent.text.match(/#verify=([^\s]+)/)[1];const row=env.DB.db.prepare('SELECT token_hash FROM auth_tokens').get();assert.equal(row.token_hash,await hash(token));await auth(request('/api/auth/verify','POST',{token}),env);assert.equal((await auth(request('/api/auth/login','POST',credentials),env)).status,200)}finally{globalThis.fetch=originalFetch}});
test('Google OAuth exchanges PKCE code and establishes verified session',async()=>{const env={...await setup(),GOOGLE_CLIENT_ID:'test-client',GOOGLE_CLIENT_SECRET:'test-secret'},originalFetch=globalThis.fetch;try{const start=await auth(request('/api/auth/google'),env),target=new URL(start.headers.get('Location'));assert.equal(target.searchParams.get('code_challenge_method'),'S256');const state=target.searchParams.get('state'),cookie=start.headers.get('Set-Cookie').split(';')[0];globalThis.fetch=async(url,options)=>{if(url.includes('/token')){assert.ok(options.body.get('code_verifier'));return Response.json({access_token:'test-access'})}return Response.json({sub:'google-user',email:'google@example.com',email_verified:true})};const callback=new Request(origin+'/api/auth/callback/google?state='+state+'&code=test-code',{headers:{Cookie:cookie}});const res=await auth(callback,env);assert.equal(res.status,303);assert.equal(env.DB.db.prepare("SELECT email_verified FROM users WHERE google_sub='google-user'").get().email_verified,1);assert.equal((await auth(callback,env)).status,400)}finally{globalThis.fetch=originalFetch}});
test('stale browser account cannot upload after another tab changes session',async()=>{const env=await setup();const req=request('/api/athletes','POST',{id:'athlete-stale',name:'Stale account'},'token-user-two');req.headers.set('X-RaceSplit-Account','user-one');assert.equal((await data(req,env)).status,403)});
test('stale account read cannot mix another account cloud history',async()=>{const env=await setup();const req=request('/api/races','GET',null,'token-user-two');req.headers.set('X-RaceSplit-Account','user-one');assert.equal((await data(req,env)).status,403)});
