import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {JSDOM} from 'jsdom';import {parseTarget,formatTarget,cumulative,importRace,applyRuns,starterTargets,startTargets} from '../public/modules/targets.mjs';
const stages=[{name:'Run 1 · 160 m',type:'run'},{name:'Row · 500 m',type:'work'},{name:'Run 2 · 160 m',type:'run'},{name:'Transition 1',type:'transition'}];
test('target times parse safely, including blanks and hours',()=>{assert.equal(parseTarget('02:30'),150000);assert.equal(parseTarget('90'),90000);assert.equal(parseTarget('01:02:03.4'),3723400);assert.equal(parseTarget(''),null);for(const v of ['abc','00:00','-1:20','02:80','1:60:00'])assert.throws(()=>parseTarget(v));assert.equal(formatTarget(150400),'02:30.4');});
test('saved-race import copies durations without mutating its source and rejects mismatches',()=>{const race={stages,ends:[60000,180000,245000,255000]},before=JSON.stringify(race);const values=importRace(race,stages);assert.deepEqual(values,[60000,120000,65000,10000]);values[0]=1;assert.equal(JSON.stringify(race),before);assert.throws(()=>importRace(race,[...stages].reverse()));assert.throws(()=>importRace({...race,ends:[60000,50000]},stages));assert.deepEqual(importRace({...race,ends:[60000]},stages),[60000,null,null,null]);});
test('bulk run editing preserves stations and transitions; cumulative requires complete preceding splits',()=>{const p={display:'both',goal:[10,20,30,40],pr:[11,21,31,41]},before=JSON.stringify(p),out=applyRuns(p,stages,60000,'both');assert.deepEqual(out.goal,[60000,20,60000,40]);assert.deepEqual(out.pr,[60000,21,60000,41]);assert.equal(JSON.stringify(p),before);assert.equal(cumulative([60000,120000,65000],1),180000);assert.equal(cumulative([60000,null,65000],2),null);});
test('target setup imports, adjusts, cancels, persists and compares without changing timing or saved races',()=>{
 const dom=new JSDOM(readFileSync(new URL('../public/index.html',import.meta.url),'utf8'),{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
 const original={window:globalThis.window,document:globalThis.document,localStorage:globalThis.localStorage,Option:globalThis.Option};Object.assign(globalThis,{window:w,document:w.document,localStorage:w.localStorage,Option:w.Option});
 const $=id=>w.document.getElementById(id);$('targetsDialog').showModal=()=>$('targetsDialog').setAttribute('open','');$('targetsDialog').close=()=>$('targetsDialog').removeAttribute('open');
 const race={event:{id:'mile',name:'DEKA MILE'},athlete:'Emma',stages,ends:[60000,180000,245000,255000],savedAt:'2026-10-10T00:00:00Z',finished:true};const history=[race],before=JSON.stringify(history);let context={event:race.event,stages,athlete:'Emma',athleteId:'emma',start:1000,ends:[],finished:false,elapsed:20000,splitElapsed:20000};
 const bridge={getTimingContext:()=>context,getHistory:()=>history};w.localStorage.setItem('racesplit-v3','untouched timing state');
 try{
 startTargets(bridge);$('setupTargets').click();assert.equal($('target-goal-0').value,'00:55');assert.equal($('target-pr-0').value,'');assert.equal($('runTargetTime').value,'00:55');assert.match($('starterHelp').textContent,/estimates/);w.document.querySelector('[aria-label="Increase Run 1 · 160 m GOAL by 5 seconds"]').click();assert.equal($('target-goal-0').value,'01:00');w.document.querySelector('[aria-label="Decrease Run 1 · 160 m GOAL by 5 seconds"]').click();assert.equal($('target-goal-0').value,'00:55');$('cancelTargets').click();assert.equal(w.localStorage.getItem('racesplit-targets-v1'),null);$('setupTargets').click();$('targetSource').value='0';$('targetImportKind').value='both';$('loadTargetRace').click();assert.equal($('target-goal-1').value,'02:00');$('runTargetTime').value='01:10';$('runTargetKind').value='goal';$('applyRunTargets').click();assert.equal($('target-goal-0').value,'01:10');assert.equal($('target-goal-2').value,'01:10');assert.equal($('target-goal-1').value,'02:00');$('target-goal-1').value='01:55';$('saveTargets').click();assert.equal($('targetsDialog').hasAttribute('open'),false);assert.match($('splitTargets').textContent,/Goal01:10/);assert.match($('splitTargets').textContent,/PR01:00/);assert.ok($('splitTargets').querySelector('[data-state=below]'));assert.equal(JSON.stringify(history),before);assert.equal(w.localStorage.getItem('racesplit-v3'),'untouched timing state');const saved=w.localStorage.getItem('racesplit-targets-v1');
 $('setupTargets').click();$('target-goal-0').value='00:20';$('cancelTargets').click();assert.equal(w.localStorage.getItem('racesplit-targets-v1'),saved);$('setupTargets').click();assert.equal($('target-goal-0').value,'01:10');$('cancelTargets').click();
 context={...context,ends:[80000],elapsed:90000,splitElapsed:10000};w.dispatchEvent(new w.Event('racesplit-view'));assert.match($('totalTargets').textContent,/Goal03:05/);assert.match($('splitTargets').textContent,/Goal01:55/);
 context={...context,elapsed:185000,splitElapsed:115000};w.dispatchEvent(new w.Event('racesplit-view'));assert.equal($('totalTargets').querySelector('.target-compare').dataset.state,'equal');assert.equal($('splitTargets').querySelector('.target-compare').dataset.state,'equal');assert.match($('totalTargets').querySelector('strong').getAttribute('aria-label'),/exactly on target/);
 context={...context,finished:true,ends:[80000,190000,260000,280000],elapsed:280000};w.dispatchEvent(new w.Event('racesplit-view'));assert.equal($('splitTargets').textContent,'');assert.ok($('totalTargets').querySelector('[data-state=over]'));assert.equal($('totalTargets').textContent.includes('remaining'),false);
 context={...context,athlete:'Az',athleteId:'az'};w.dispatchEvent(new w.Event('racesplit-view'));assert.equal($('totalTargets').textContent,'');context={...context,athlete:'Emma',athleteId:'emma'};w.dispatchEvent(new w.Event('racesplit-view'));assert.match($('totalTargets').textContent,/Goal/);
 }finally{Object.assign(globalThis,original);w.close();}
});

test('starter targets fit built-in distances, transitions and stations; custom events stay blank',()=>{assert.deepEqual(starterTargets({id:'mile'},stages),[55000,90000,55000,10000]);assert.deepEqual(starterTargets({id:'fit'},stages),[150000,90000,150000,10000]);assert.deepEqual(starterTargets({id:'hyrox'},stages),[300000,240000,300000,10000]);assert.deepEqual(starterTargets({id:'strong'},[{name:'Lunges',type:'work'},{name:'Transition',type:'transition'},{name:'Row',type:'work'}]),[90000,10000,120000]);assert.deepEqual(starterTargets({id:'custom'},stages),[null,null,null,null]);});
